# Generated by Django 3.2.4 on 2021-12-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_commonuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
