# Generated by Django 3.2.4 on 2021-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_commonuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('google', 'google'), ('kakao', 'kakao')], default='email', max_length=6),
        ),
    ]
