# Generated by Django 3.2.4 on 2022-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_resetpasswordcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordcode',
            name='used',
        ),
        migrations.AddField(
            model_name='resetpasswordcode',
            name='status',
            field=models.CharField(choices=[('expired', 'expired'), ('used', 'used'), ('active', 'active')], default='active', max_length=7),
        ),
    ]
