# Generated by Django 3.2.4 on 2021-12-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20211211_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.teammember'),
        ),
    ]
