# Generated by Django 3.2.4 on 2021-12-12 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20211211_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='company',
        ),
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.team'),
        ),
    ]
