# Generated by Django 3.2.4 on 2021-12-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20211212_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='team',
        ),
        migrations.AddField(
            model_name='invite',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.party'),
        ),
    ]
