# Generated by Django 3.2.4 on 2021-07-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20210701_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
