# Generated by Django 3.2.4 on 2021-12-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20211212_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
