# Generated by Django 3.2.4 on 2021-07-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210701_1405'),
        ('group', '0007_auto_20210701_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='store',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.menu')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.party')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.vote'),
        ),
    ]
