# Generated by Django 3.2.4 on 2021-12-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_invite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.SmallIntegerField(default=2),
        ),
    ]
