# Generated by Django 3.2.4 on 2021-07-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_alter_contract_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='party',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
