# Generated by Django 3.2.4 on 2021-12-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_auto_20211213_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
