# Generated by Django 3.2.4 on 2021-12-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20211223_0105'),
        ('group', '0013_alter_teammember_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.party')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.teammember')),
            ],
        ),
    ]
