# Generated by Django 3.2.4 on 2021-07-15 15:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_company_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lon',
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
