# Generated by Django 3.2.4 on 2021-12-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='group.party'),
        ),
    ]
