# Generated by Django 3.2.4 on 2022-01-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_auto_20220105_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='closed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
