# Generated by Django 3.2.4 on 2022-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_auto_20220106_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
