# Generated by Django 3.2.4 on 2021-07-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_alter_contract_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='vote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.vote'),
        ),
    ]
