# Generated by Django 3.2.4 on 2021-07-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0019_alter_membership_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='party',
        ),
        migrations.AddField(
            model_name='vote',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='group.membership'),
        ),
    ]
