# Generated by Django 3.2.4 on 2022-01-16 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0021_auto_20220116_1312'),
        ('stores', '0002_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.keyword'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.crew'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.keyword'),
        ),
        migrations.AddField(
            model_name='crewmembership',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_membership', to='group.crew'),
        ),
        migrations.AddField(
            model_name='crewmembership',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.teammember'),
        ),
        migrations.AddField(
            model_name='crewmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crew',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.team'),
        ),
        migrations.AddField(
            model_name='vote',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.lunch'),
        ),
    ]
