# Generated by Django 3.2.4 on 2022-01-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0022_auto_20220116_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunch',
            name='date',
        ),
        migrations.RemoveField(
            model_name='party',
            name='date',
        ),
        migrations.AddField(
            model_name='crewmembership',
            name='invite_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_sender_profile', to='group.teammember'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='invite_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_sender_profile', to='group.teammember'),
        ),
        migrations.AlterField(
            model_name='crewmembership',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_team_profile', to='group.teammember'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_team_profile', to='group.teammember'),
        ),
    ]
