# Generated by Django 3.2.4 on 2022-01-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_auto_20220125_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
