# Generated by Django 3.2.4 on 2022-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0027_alter_party_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
