# Generated by Django 3.2.4 on 2022-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0028_alter_lunch_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
