# Generated by Django 3.2.4 on 2021-07-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210712_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
