# Generated by Django 3.2.4 on 2021-12-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20211210_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='store_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
