# Generated by Django 3.2.4 on 2021-12-23 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20211210_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 23, 1, 5, 57, 97719)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
