# Generated by Django 3.2.4 on 2022-01-27 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0026_crew_created_at'),
        ('stores', '0002_keyword'),
        ('reviews', '0006_auto_20211223_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='address',
        ),
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location',
        ),
        migrations.RemoveField(
            model_name='review',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='review',
            name='price',
        ),
        migrations.RemoveField(
            model_name='review',
            name='public',
        ),
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
        migrations.RemoveField(
            model_name='review',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.keyword'),
        ),
        migrations.AddField(
            model_name='review',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.teammember'),
        ),
    ]
