# Generated by Django 3.2.4 on 2022-06-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_keyword_good_count'),
        ('reviews', '0007_auto_20220127_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.keyword'),
        ),
    ]
