# Generated by Django 3.2.4 on 2022-06-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_keyword_good_count'),
        ('reviews', '0008_alter_review_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_image', to='stores.keyword'),
        ),
    ]
