# Generated by Django 3.2.4 on 2022-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220606_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(default=3),
        ),
    ]
