# Generated by Django 3.2.4 on 2022-01-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0021_auto_20220116_1312'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('hit_count', models.IntegerField(default=0)),
                ('eat_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.team')),
            ],
        ),
    ]
