# Generated by Django 3.2.4 on 2021-07-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210701_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='stores/menu'),
        ),
    ]
