# Generated by Django 3.2.4 on 2022-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
    ]
