# Generated by Django 3.2.4 on 2021-07-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='store',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
