# Generated by Django 3.2.4 on 2021-07-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20210705_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
