# Generated by Django 3.2.4 on 2021-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20210705_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
