# Generated by Django 3.2.4 on 2021-07-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
