# Generated by Django 3.2.4 on 2021-07-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
    ]
