# Generated by Django 3.2.4 on 2021-07-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_rename_menu_name_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='star',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
