# Generated by Django 3.2.4 on 2021-07-15 14:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='store',
            name='star',
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
