# Generated by Django 3.2.4 on 2021-07-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_auto_20210715_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='store',
            name='lon',
        ),
    ]
